services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx configuration
      - ./certs:/etc/nginx/certs:ro         # SSL certificates (read-only)
    depends_on:
      - uwazi-api

  uwazi-api:
    build:
      context: .
    container_name: uwazi-api
    env_file:
      - .env
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - .:/app  # Mount current directory to container
      - /app/venv  # Avoid overwriting virtual environment in Docker
    depends_on:
      - uwazi-db
    command: >
      sh -c "flask run --host=0.0.0.0 --port=${FLASK_PORT} --reload"
        
  uwazi-db:
    image: postgres:latest
    container_name: uwazi-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"  # Default PostgreSQL port
    volumes:
      - uwazi-db-data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL data

volumes:
  uwazi-db-data:
