services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf  # Nginx configuration
      - ./config/nginx/certs:/etc/nginx/certs:ro         # SSL certificates (read-only)
    depends_on:
      - api

  api:
    build:
      context: .
    container_name: api
    env_file:
      - .env
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - .:/app  # Mount current directory to container
    depends_on:
      - database
    command: >
      sh -c "flask run --host=0.0.0.0 --port=${FLASK_PORT} --reload"\
       
  database:
    image: postgres:latest
    container_name: database
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"  # Default PostgreSQL port
    volumes:
      - database-data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL data

volumes:
  database-data:
