version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
      - "8443:8443"
      - "8000:8000"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf  # Nginx configuration
      - ./config/nginx/certs:/etc/nginx/certs:ro         # SSL certificates (read-only)
      - ./frontend:/var/html/uwazi-frontend              # Folder that serves the frontend's static files
    depends_on:                                         #ensures  that api services starts before NGINX 
      - api                                          


  api:
    build:
      context: .
    container_name: api
    environment:
      - DATABASE_URL=postgresql://uwazi_admin:Today123%!@database:5432/uwazi_db
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - .:/app  # Mount project directory to live updates 
    depends_on: # #ensures  that database starts before api
      - database
    command: ["wait-for-it", "database:5432", "--timeout=60", "--", "flask", "run", "--host=0.0.0.0", "--port=${FLASK_PORT}", "--reload"]

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: uwazi_admin
      POSTGRES_PASSWORD: Today123%!
      POSTGRES_DB: uwazi_db
    ports:
      - "5432:5432"  # Default PostgreSQL port defined in .env file
    volumes:
      - database-data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL data. 
  
  docs:
    build:
      context: ./docs/website
    container_name: docs
    ports:
      - "4000:4000"

volumes:
  database-data:
