services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
      - "8443:8443"
      - "8000:8000"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf  # Nginx configuration
      - ./config/nginx/certs:/etc/nginx/certs:ro         # SSL certificates (read-only)
      - ./frontend:/var/html/uwazi-frontend              # Folder that serves the frontend's static files
    depends_on:
      - api

  api:
    build:
      context: .
    container_name: api
    env_file:
      - .env
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - .:/app  # Mount current directory into docker container
    depends_on:
      - database
    command: >
      sh -c "flask run --host=0.0.0.0 --port=${FLASK_PORT} --reload"\
       
  database:
    image: postgres:latest
    container_name: database
    env_file:
      - .env
    ports:
      - "5432:5432"  # Default PostgreSQL port defined in .env file
    volumes:
      - database-data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL data. This will persist data even if container is deleted.

  docs:
    build:
      context: ./docs/website
    container_name: docs
    ports:
      - "4000:4000"

volumes:
  database-data:
